branch-defaults:
  prod:
    environment: Turtrack-server-env
option_settings:
  aws:autoscaling:launchconfiguration:
    LaunchTemplateEnabled: true
global:
  application_name: turtrack-server
  default_region: us-east-1
  platform: java
  workspace_type: Application
