name: Build and Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - prod

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact_name: ${{ steps.build_info.outputs.artifact_name }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        env:
          SPRING_PROFILES_ACTIVE: prod
        run: mvn clean test package -Dspring.profiles.active=prod

      - name: Set build info
        id: build_info
        run: echo "artifact_name=application-${{ github.sha }}.jar" >> $GITHUB_OUTPUT

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.build_info.outputs.artifact_name }}
          path: target/*.jar
          retention-days: 5

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.build.outputs.artifact_name }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Elastic Beanstalk CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-dev
          pip3 install awsebcli --upgrade

      - name: Deploy to Elastic Beanstalk
        run: |
          chmod +x .github/scripts/deploy-to-eb.sh
          .github/scripts/deploy-to-eb.sh
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          ARTIFACT_NAME: ${{ needs.build.outputs.artifact_name }}