name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - prod  # Trigger the pipeline on pushes to the prod branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Build the JAR file
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # Step 4: Configure AWS CLI
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 5: Deploy to Elastic Beanstalk
      - name: Deploy to Elastic Beanstalk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          EB_APP_NAME="turtrack-server"
          EB_ENV_NAME="Turtrack-server-env"
          VERSION_LABEL=$GITHUB_SHA
          JAR_FILE="target/turtrack-manager-0.0.1-SNAPSHOT.jar"

          # Create a ZIP file containing the JAR
          mkdir deploy
          cp $JAR_FILE deploy/
          zip -r app.zip deploy/

          # Initialize EB CLI and deploy
          eb init $EB_APP_NAME --platform java --region $AWS_REGION
          eb use $EB_ENV_NAME
          eb deploy --label $VERSION_LABEL
